/**
 * Sample meter data for initialization.
 */
const meterData = [
  {
    address_1: '45 Fjordveien',
    address_2: 'Hus B',
    address_3: 'Sentrum',
    address_4: 'Oslo, NO-0250',
    application_status: 'Approved',
    balance_due: 67.89,
    bookmark: 'BMK56789',
    book_no: 'B002',
    connection_id: 'CONN789123',
    consumer_meter_reader_note: 'Possible pipe issue, check for moisture',
    days: 28,
    dials: 7,
    estimated_units: 980,
    estimates_count: '2',
    fixed_charges: '18.75',
    house_key: 'HK002',
    last_days: '27',
    legal_description_1: 'Gnr 124, Bnr 5',
    legal_description_2: 'Bakke residential area',
    location_address_1: '12 Elvegata',
    location_address_2: 'Local 5',
    meter_detail: 'Type B, Model Y',
    meter_id: 'MT789123',
    meter_location_01: 'Backyard',
    meter_location_02: 'Under stairs',
    meter_location_03: 'Basement',
    meter_reader_note: 'Easy access',
    meter_reader_note_2: 'Access requires a code',
    meter_size: '2 inch',
    meter_type: 'Analog',
    multiplier: '1.30',
    name_1: 'Ola Nordmann',
    name_2: 'Kari Nordmann',
    new_reading: null,
    previous_reading: 1580,
    previous_units: 180,
    rapid_no: 'R567890',
    read_sequence: 'SEQ234',
    record_key: 'RK123789',
    restrictor_size: '2.5 inch',
    special_read_date: '2024-03-05',
    special_read_type: 'Regular',
    status: 'Active',
    supply_charges: '12.50',
    supply_tariff: 3,
    surname_initials: 'O.N.',
    tariff: 'Standard',
    tariff_description: 'Regular residential tariff',
    trade_name: 'Fjord Utilities',
    update_time: '2024-03-05T14:40:00Z',
    user_alpha_01: 'UA456',
    valuation_number_01: 'VN78901'
  },
  {
    address_1: '78 Kystveien',
    address_2: 'Apt. 302',
    address_3: 'Bryggen',
    address_4: 'Bergen, NO-5003',
    application_status: 'Pending',
    balance_due: 32.45,
    bookmark: 'BMK67890',
    book_no: 'B003',
    connection_id: 'CONN456789',
    consumer_meter_reader_note: 'Possible leakage in basement, inspect water stains',
    days: 31,
    dials: 5,
    estimated_units: 1350,
    estimates_count: '4',
    fixed_charges: '20.00',
    house_key: 'HK003',
    last_days: '30',
    legal_description_1: 'Gnr 78, Bnr 12',
    legal_description_2: 'Bryggen residential complex',
    location_address_1: '99 Fjelltunet',
    location_address_2: 'House 8',
    meter_detail: 'Type C, Model Z',
    meter_id: 'MT456789',
    meter_location_01: 'Garage',
    meter_location_02: 'Rooftop terrace',
    meter_location_03: 'Behind stairs',
    meter_reader_note: 'Difficult access',
    meter_reader_note_2: 'Special key required',
    meter_size: '1 inch',
    meter_type: 'Smart',
    multiplier: '1.15',
    name_1: 'Erik Hansen',
    name_2: 'Lise Berg',
    new_reading: null,
    previous_reading: 1370,
    previous_units: 130,
    rapid_no: 'R234567',
    read_sequence: 'SEQ567',
    record_key: 'RK345678',
    restrictor_size: '1.75 inch',
    special_read_date: '2024-03-05',
    special_read_type: 'Emergency',
    status: 'Pending',
    supply_charges: '9.50',
    supply_tariff: 1,
    surname_initials: 'E.H.',
    tariff: 'Small household',
    tariff_description: 'Apartment residential tariff',
    trade_name: 'Vest Utilities',
    update_time: '2024-03-05T14:50:00Z',
    user_alpha_01: 'UA789',
    valuation_number_01: 'VN23456'
  },
  {
    address_1: '21 Skogveien',
    address_2: '',
    address_3: 'Suburb',
    address_4: 'Trondheim, NO-7013',
    application_status: 'Completed',
    balance_due: 0.00,
    bookmark: 'BMK89012',
    book_no: 'B004',
    connection_id: 'CONN678901',
    consumer_meter_reader_note: 'Everything in order',
    days: 29,
    dials: 6,
    estimated_units: 1100,
    estimates_count: '1',
    fixed_charges: '14.00',
    house_key: 'HK004',
    last_days: '28',
    legal_description_1: 'Gnr 21, Bnr 7',
    legal_description_2: 'Skogveien housing cooperative',
    location_address_1: '10 Elgveien',
    location_address_2: '',
    meter_detail: 'Type A, Model X',
    meter_id: 'MT678901',
    meter_location_01: 'By main entrance',
    meter_location_02: 'In storage room',
    meter_location_03: 'Side wall',
    meter_reader_note: 'Easy to read',
    meter_reader_note_2: 'No special key required',
    meter_size: '1.25 inch',
    meter_type: 'Digital',
    multiplier: '1.10',
    name_1: 'Per Andersen',
    name_2: 'Marit Olsen',
    new_reading: null,
    previous_reading: 1300,
    previous_units: 120,
    rapid_no: 'R890123',
    read_sequence: 'SEQ890',
    record_key: 'RK567890',
    restrictor_size: '2 inch',
    special_read_date: '2024-03-05',
    special_read_type: 'Routine',
    status: 'Completed',
    supply_charges: '11.25',
    supply_tariff: 2,
    surname_initials: 'P.A.',
    tariff: 'Regular household',
    tariff_description: 'Standard residential tariff',
    trade_name: 'Midt Utilities',
    update_time: '2024-03-05T15:00:00Z',
    user_alpha_01: 'UA012',
    valuation_number_01: 'VN67890'
  },
  {
    address_1: '33 Havnegata',
    address_2: 'Building C',
    address_3: 'Port District',
    address_4: 'Stavanger, NO-4006',
    application_status: 'Pending',
    balance_due: 55.30,
    bookmark: 'BMK123987',
    book_no: 'B005',
    connection_id: 'CONN987654',
    consumer_meter_reader_note: 'Check meter seal, may be loose',
    days: 27,
    dials: 6,
    estimated_units: 1050,
    estimates_count: '2',
    fixed_charges: '16.25',
    house_key: 'HK005',
    last_days: '26',
    legal_description_1: 'Gnr 99, Bnr 3',
    legal_description_2: 'Havnegata residential block',
    location_address_1: '18 Sjøveien',
    location_address_2: 'Office 201',
    meter_detail: 'Type A, Model Z',
    meter_id: 'MT987654',
    meter_location_01: 'Entrance hallway',
    meter_location_02: 'Left side of building',
    meter_location_03: 'Maintenance room',
    meter_reader_note: 'Requires access card',
    meter_reader_note_2: 'Might need assistance from staff',
    meter_size: '1.5 inch',
    meter_type: 'Digital',
    multiplier: '1.20',
    name_1: 'Torvald Eriksen',
    name_2: 'Signe Eriksen',
    new_reading: null,
    previous_reading: 1500,
    previous_units: 145,
    rapid_no: 'R765432',
    read_sequence: 'SEQ345',
    record_key: 'RK654321',
    restrictor_size: '2 inch',
    special_read_date: '2024-03-05',
    special_read_type: 'Routine',
    status: 'Active',
    supply_charges: '13.00',
    supply_tariff: 2,
    surname_initials: 'T.E.',
    tariff: 'Standard',
    tariff_description: 'Regular residential tariff',
    trade_name: 'Nord Utilities',
    update_time: '2024-03-05T15:10:00Z',
    user_alpha_01: 'UA567',
    valuation_number_01: 'VN56789'
  },
  {
    address_1: '50 Skagenveien',
    address_2: 'Unit 12B',
    address_3: 'Seaside Area',
    address_4: 'Tromsø, NO-9008',
    application_status: 'Completed',
    balance_due: 0.00,
    bookmark: 'BMK890765',
    book_no: 'B006',
    connection_id: 'CONN543210',
    consumer_meter_reader_note: 'Inspect for frost damage',
    days: 30,
    dials: 7,
    estimated_units: 1275,
    estimates_count: '3',
    fixed_charges: '19.50',
    house_key: 'HK006',
    last_days: '29',
    legal_description_1: 'Gnr 112, Bnr 4',
    legal_description_2: 'Skagenveien housing complex',
    location_address_1: '22 Nordlysveien',
    location_address_2: 'Apartment 7',
    meter_detail: 'Type B, Model Y',
    meter_id: 'MT543210',
    meter_location_01: 'Utility closet',
    meter_location_02: 'Under stairwell',
    meter_location_03: 'Outdoor shed',
    meter_reader_note: 'May be frozen, check before opening',
    meter_reader_note_2: 'Residents report occasional low pressure',
    meter_size: '2 inch',
    meter_type: 'Analog',
    multiplier: '1.35',
    name_1: 'Henrik Solberg',
    name_2: 'Elin Solberg',
    new_reading: null,
    previous_reading: 1710,
    previous_units: 180,
    rapid_no: 'R345678',
    read_sequence: 'SEQ678',
    record_key: 'RK432109',
    restrictor_size: '2.5 inch',
    special_read_date: '2024-03-05',
    special_read_type: 'Regular',
    status: 'Completed',
    supply_charges: '15.25',
    supply_tariff: 3,
    surname_initials: 'H.S.',
    tariff: 'Large household',
    tariff_description: 'High usage residential tariff',
    trade_name: 'Arctic Water Services',
    update_time: '2024-03-05T15:20:00Z',
    user_alpha_01: 'UA890',
    valuation_number_01: 'VN34567'
  },
  {
    address_1: '14 Bjørneveien',
    address_2: 'House 5',
    address_3: 'Forest District',
    address_4: 'Lillehammer, NO-2609',
    application_status: 'Pending',
    balance_due: 28.75,
    bookmark: 'BMK654321',
    book_no: 'B007',
    connection_id: 'CONN210987',
    consumer_meter_reader_note: 'Check for vegetation blocking the meter',
    days: 32,
    dials: 5,
    estimated_units: 1150,
    estimates_count: '2',
    fixed_charges: '17.00',
    house_key: 'HK007',
    last_days: '31',
    legal_description_1: 'Gnr 76, Bnr 9',
    legal_description_2: 'Bjørneveien housing association',
    location_address_1: '30 Granittveien',
    location_address_2: '',
    meter_detail: 'Type C, Model X',
    meter_id: 'MT210987',
    meter_location_01: 'Behind the garage',
    meter_location_02: 'Near garden fence',
    meter_location_03: 'Under wooden deck',
    meter_reader_note: 'Overgrown bushes, bring clippers if necessary',
    meter_reader_note_2: 'Mud around the meter, wear boots',
    meter_size: '1.25 inch',
    meter_type: 'Smart',
    multiplier: '1.10',
    name_1: 'Johan Fredriksen',
    name_2: 'Sofia Fredriksen',
    new_reading: null,
    previous_reading: 1485,
    previous_units: 130,
    rapid_no: 'R901234',
    read_sequence: 'SEQ901',
    record_key: 'RK876543',
    restrictor_size: '1.75 inch',
    special_read_date: '2024-03-05',
    special_read_type: 'Emergency',
    status: 'Pending',
    supply_charges: '10.75',
    supply_tariff: 1,
    surname_initials: 'J.F.',
    tariff: 'Small household',
    tariff_description: 'Single-family house tariff',
    trade_name: 'Nordic Water Utility',
    update_time: '2024-03-05T15:30:00Z',
    user_alpha_01: 'UA345',
    valuation_number_01: 'VN90123'
  }
]

export default meterData
